version: '3.8'
services: 
  backend:
    image: ec2-13-51-6-86.eu-north-1.compute.amazonaws.com:5500/admin/backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHONPATH=/app
        - DJANGO_SETTINGS_MODULE=admin/settings.py
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    depends_on:
      - db
  
  queue:
    image: ec2-13-51-6-86.eu-north-1.compute.amazonaws.com:5500/admin/queue
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - .dbdata:/var/lib/mysql 
    ports:
      - 33066:3306

      
